[package]
name = "random_component"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { workspace = true }
cc = { workspace = true }

[features]
default = []

[lib]
crate-type = ["cdylib", "lib"]
